
name: damodrop
description: اپلیکیشن جمع‌آوری ایردراپ
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  walletconnect_flutter: ^1.0.4

assets:
  - assets/lang/fa.json
  - assets/lang/en.json
